env:
  global:
    - CC_TEST_REPORTER_ID=de8368d6af22c809a4598f7bf0e310787998e31d0366cd374118749581800ff5
language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  composer test
install:
  - composer install --prefer-source --no-interaction
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
